---
excludes:
  paths:
  - pattern: "3RD-PARTY-NOTICES.txt"
    reason: "OTHER"
    comment: "File including 3rd party license notices."

  - pattern: "example-adapter/**"
    reason: "EXAMPLE_OF"
    comment: "This directory contains an example app that's not distributed."

  - pattern: "examples/**"
    reason: "EXAMPLE_OF"
    comment: "This directory contains examples that are not distributed."

  - pattern: "documentation/**"
    reason: "DOCUMENTATION_OF"
    comment: "This directory contains documentation that's not distributed."

  scopes:
  - pattern: "checkstyle"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages for code styling checks (testing) only."

  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "jacocoAgent"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "jacocoAnt"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."

  - pattern: "annotationProcessor"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileClasspath"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileOnly"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "provided"
    reason: "RUNTIME_DEPENDENCY_OF"
    comment: "Packages that are provided by the runtime."

license_choices:
  repository_license_choices:
    - given: "GPL-2.0-only OR Apache-2.0"
      choice: "Apache-2.0"
    - given: "GPL-2.0-only OR BSD-3-Clause"
      choice: "BSD-3-Clause"
    - given: "GPL-2.0-only OR CDDL-1.1"
      choice: "CDDL-1.1"
    - given: "CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0"
      choice: "CDDL-1.1"
    - given: "GPL-2.0-only OR CDDL-1.0"
      choice: "CDDL-1.0"

curations:
  packages:
    - id: "Maven:com.sun.xml.messaging.saaj:saaj-impl:1.3.28"
      curations:
        comment: "The package offers GPL-2.0-only OR CDDL-1.1 and we use the curation to override the choice mechanism due to a pending issue in ORT."
        concluded_license: "CDDL-1.1"

resolutions:
  rule_violations:
    - message: "copyleft-strong license GPL-3.0-only in Maven:gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are related to a Gradle plugin and are not distributed with XRd4J."
    - message: "copyleft-strong license GPL-3.0-or-later in Maven:gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are related to a Gradle plugin and are not distributed with XRd4J."
    - message: "copyleft-strong license GPL-2.0-only in Maven:gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are related to a Gradle plugin and are not distributed with XRd4J."
    - message: "copyleft-strong license GPL-2.0-or-later in Maven:gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are related to a Gradle plugin and are not distributed with XRd4J."
    - message: "copyleft-strong license GPL-2.0-or-later in Maven:org.jetbrains.kotlin:kotlin-compiler-embeddable:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:org.jetbrains.kotlin:kotlin-compiler-embeddable:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J."
    - message: "copyleft-strong license GPL-3.0-or-later in Maven:org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J."
    - message: "The declared license 'GNU LPGL 3' could not be mapped to a valid license or parsed as an SPDX expression. The license was found in package Maven:org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J."
    - message: "Unhandled license LicenseRef-scancode-capec-tou in Maven:org.owasp:dependency-check-core:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J."
    - message: "Unhandled license LicenseRef-scancode-cc-sa-1.0 in Maven:org.apache.lucene:lucene-core:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J. The files are related to the OWASP Dependency Check plugin."
    - message: "Unhandled license LicenseRef-scancode-cc-sa-1.0 in Maven:org.apache.lucene:lucene-analyzers-common:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J. The files are related to the OWASP Dependency Check plugin."
    - message: "Unhandled license LicenseRef-scancode-cc-sa-1.0 in Maven:org.apache.lucene:lucene-queryparser:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J. The files are related to the OWASP Dependency Check plugin."
    - message: "Unhandled license LicenseRef-scancode-cc-sa-1.0 in Maven:org.apache.lucene:lucene-queries:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J. The files are related to the OWASP Dependency Check plugin."
    - message: "Unhandled license LicenseRef-scancode-cc-sa-1.0 in Maven:org.apache.lucene:lucene-sandbox:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J. The files are related to the OWASP Dependency Check plugin."
    - message: "The declared license 'Common Public 1.0' could not be mapped to a valid license or parsed as an SPDX expression. The license was found in package Maven:org.whitesource:pecoff4j:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J. The files are related to the OWASP Dependency Check plugin."
    - message: "The declared license 'ASL2' could not be mapped to a valid license or parsed as an SPDX expression. The license was found in package Maven:org.sonatype.ossindex:ossindex-service-client:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J. The files are related to the OWASP Dependency Check plugin."
    - message: "The declared license 'ASL2' could not be mapped to a valid license or parsed as an SPDX expression. The license was found in package Maven:org.sonatype.ossindex:ossindex-service-api:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J. The files are related to the OWASP Dependency Check plugin."
    - message: "The declared license 'ASL2' could not be mapped to a valid license or parsed as an SPDX expression. The license was found in package Maven:org.sonatype.goodies:package-url-java:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not distributed with XRd4J. The files are related to the OWASP Dependency Check plugin."