---
excludes:
  paths:
  - pattern: "3RD-PARTY-NOTICES.txt"
    reason: "OTHER"
    comment: "File including 3rd party license notices."

  - pattern: "src/**"
    reason: "OTHER"
    comment: "This directory contains the library which use this example app demonstrates."

  - pattern: "examples/**"
    reason: "EXAMPLE_OF"
    comment: "This directory contains examples that are not distributed."

  - pattern: "documentation/**"
    reason: "DOCUMENTATION_OF"
    comment: "This directory contains documentation that's not distributed."

  scopes:
  - pattern: "checkstyle"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages for code styling checks (testing) only."

  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "jacocoAgent"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "jacocoAnt"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."

  - pattern: "annotationProcessor"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileClasspath"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileOnly"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "provided"
    reason: "RUNTIME_DEPENDENCY_OF"
    comment: "Packages that are provided by the runtime."

license_choices:
  repository_license_choices:
    - given: "GPL-2.0-only OR Apache-2.0"
      choice: "Apache-2.0"
    - given: "GPL-2.0-only OR BSD-3-Clause"
      choice: "BSD-3-Clause"
    - given: "GPL-2.0-only OR CDDL-1.1"
      choice: "CDDL-1.1"
    - given: "CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0"
      choice: "CDDL-1.1"
    - given: "GPL-2.0-only OR CDDL-1.0"
      choice: "CDDL-1.0"

curations:
  packages:
    - id: "Maven:com.sun.xml.messaging.saaj:saaj-impl:1.3.28"
      curations:
        comment: "The package offers GPL-2.0-only OR CDDL-1.1 and we use the curation to override the choice mechanism due to a pending issue in ORT."
        concluded_license: "CDDL-1.1"
    - id: "Maven:org.yaml:snakeyaml:1.33"
      curations:
        comment: "The Apache-2.0 licensed package has a file which also offers a choice of multiple other licenses and we use the curation to override the choice mechanism due to a pending issue in ORT."
        concluded_license: "Apache-2.0"