/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "example-adapter"

dependencyResolutionManagement {
    versionCatalogs {
        create("xrd4j") {
            from(files("../src/gradle/libs.versions.toml"))
        }
    }
}
